wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1650376224
    t:
      1:
      - 1
      - 9
      - 50
      - 55
      2:
      - 1
      - 9
      - 50
      - 55
      3:
      - 1
      4: 3.9.12
      5: 0.12.14
      8:
      - 5
