irrigation:
  - goal: 0.75
    training_steps: 10000
  - goal: 1.0
    training_steps: 1000000
  - goal: 1.5
    training_steps: 1000000
  - goal: 2.0
    training_steps: 1000000
  - goal: 3.0
    training_steps: 1000000
  - goal: 4.0
    training_steps: 1000000
  - goal: 5.0
    training_steps: 1000000
