defaults:
  - core: core_1
  - start_node_selection_dqn: start_dqn_1
  - end_node_selection_dqn: end_dqn_1
  - exploratory_actions: exploratory_1
  - environment: environment_1
  - stop_conditions: stop_conditions_1

number_of_graphs: 100