defaults:
  - core: core_1
  - start_node_selection_dqn: start_dqn_1
  - end_node_selection_dqn: end_dqn_1
  - exploratory_actions: exploratory_1
  - environment: environment_1
  - stop_conditions: stop_conditions_steps_plus_edges
number_of_graphs: 10
random_seed: 50
stop_after_void_action: True
max_edges_percentage: 0.4
max_steps: 5000