defaults:
  - multi_action_q_network: default_q_net
  - environment: environment_1
  - core: core_1
number_of_graphs: 1
deterministic: true
random_seed: 873
max_steps: 300
irrigation_goal: 4.0
training_duration_in_hours: 360
validation_interval: 5000
num_dataloader_workers: 0.5
inject_irrigation: true
irrigation_compression: 3
irrigation_grid_dim: [10,10]
irrigation_grid_cell_size: [0.1,0.1]
early_stopping_patience: 10
use_hindsight: true
exclude_isolated_from_start_nodes: false
use_irrigation_improvement: false
gpu_device: 0