defaults:
  - multi_action_q_network: default_q_net
  - environment: environment_1
  - hierarchical: h_1
number_of_graphs: 1
deterministic: true
random_seed: 873
max_steps: 800
irrigation_goal: 0.75
training_duration_in_hours: 360
validation_interval: 5000
num_dataloader_workers: 0.5
inject_irrigation: true
irrigation_compression: 2
irrigation_grid_dim: [10,10]
irrigation_grid_cell_size: [0.1,0.1]