defaults:
  - core: core_1
  - multi_action_q_network: default_q_net
  - environment: environment_1
number_of_graphs: 1
deterministic: true
random_seed: 873
max_steps: 800
irrigation_goal: 2.0
training_duration_in_hours: 23
validation_interval: 5000